# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GE3c6jaiEff2oAHhw0CxudKcycD6K57i
"""

list = ["i","","a","m","","b","o","y" ]
list.reverse()
print(str(list))

def my_function(x):
  return x[::-1]

mytxt = my_function("I am a boy")

print(mytxt)